# Generated by Django 5.0.14 on 2026-08-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Square logo works best (e.g. 200x200px).', null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Marketing Graduate' or an organisation name.", max_length=150)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('message', models.TextField()),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this review without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('stat', models.CharField(blank=True, help_text="e.g. '+18% this quarter' or '2,340 openings'", max_length=50)),
                ('icon', models.CharField(blank=True, help_text='An emoji to display, e.g. 💻 📈 🏥', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trending Topic',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('learnership', 'Learnership'), ('inservice', 'In-Service Trainee'), ('bursary', 'Bursary')], default='job', max_length=20)),
                ('sector', models.CharField(choices=[('public', 'Public Sector'), ('private', 'Private Sector')], default='private', help_text="Only used for the 'Jobs' category — lets job seekers filter between Public Sector and Private Sector roles.", max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Optional banner image shown on the job card and job detail page (e.g. 800x450px, 16:9).', null=True, upload_to='job_images/')),
                ('description', models.TextField(help_text='Shown first, above the advertisement blocks.', verbose_name='Description Part 1')),
                ('description2', models.TextField(blank=True, verbose_name='Description Part 2')),
                ('description3', models.TextField(blank=True, verbose_name='Description Part 3')),
                ('description4', models.TextField(blank=True, verbose_name='Description Part 4')),
                ('description5', models.TextField(blank=True, verbose_name='Description Part 5')),
                ('location', models.CharField(help_text='e.g. Johannesburg, Gauteng', max_length=100)),
                ('salary', models.CharField(blank=True, help_text="e.g. R15,000 - R20,000 per month, or 'Market Related'", max_length=100)),
                ('deadline', models.DateField()),
                ('application_link', models.URLField(blank=True, help_text='External link the Apply button opens in a new tab. Leave blank if applicants must apply by email instead.')),
                ('application_email', models.EmailField(blank=True, help_text='Fill this in if applicants must apply by email instead of a link. It will show as a clickable, copyable email address.', max_length=254)),
                ('z83_form', models.FileField(blank=True, help_text='Upload the Z83 application form (PDF). Only shown for Public Sector jobs.', null=True, upload_to='z83_forms/', verbose_name='Z83 Form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this listing without deleting it.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
