# Generated by Django 5.2.16 on 2026-08-05 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_trendingtopic_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopic',
            name='body2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Article Body — Part 2'),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='body3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Article Body — Part 3'),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='body4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Article Body — Part 4'),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='body5',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Article Body — Part 5'),
        ),
        migrations.AlterField(
            model_name='trendingtopic',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Optional. Leave blank to keep this as a stat-only homepage card. Fill this in to publish a full article page — the homepage card automatically becomes clickable. Use the image icon in the toolbar to insert and position pictures anywhere in the text.', verbose_name='Article Body — Part 1'),
        ),
    ]
