# Generated by Django 5.2.16 on 2026-08-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_trendingtopic_body2_trendingtopic_body3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopic',
            name='image',
            field=models.ImageField(blank=True, help_text="Optional. A simple picture upload — no rich text editor needed. Shown on the homepage 'Trending' card and at the top of the full article page, if one is published.", null=True, upload_to='trending_images/', verbose_name='Featured Image'),
        ),
    ]
