# Generated by Django 5.2.16 on 2026-08-06 20:16

import django.db.models.deletion
from django.db import migrations, models


def reassign_inservice_jobs(apps, schema_editor):
    """In-Service Trainee is being removed as a category. Any existing
    jobs posted under it are reassigned to the general 'Job' category
    instead of being deleted, so they stay visible somewhere rather
    than silently disappearing from every listing page."""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(type='inservice').update(type='job')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_trendingtopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline_text',
            field=models.CharField(blank=True, help_text="Use this instead of a date when no specific deadline was given, e.g. 'Until filled', 'Open until further notice', 'Ongoing applications'. If both are filled in, this text is shown instead of the date.", max_length=100, verbose_name='Deadline (text)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, help_text="External link the Apply button opens in a new tab. Leave blank if applicants must apply by email, or if you're using Multiple Application Options below instead."),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, help_text="Leave blank if there's no fixed date — use Deadline (text) below instead.", null=True),
        ),
        migrations.RunPython(reassign_inservice_jobs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('learnership', 'Learnership'), ('bursary', 'Bursary')], default='job', max_length=20),
        ),
        migrations.CreateModel(
            name='JobApplicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Marketing Internship', 'Finance Internship — Cape Town'", max_length=150)),
                ('url', models.URLField(help_text="Where this specific option's Apply button goes.", verbose_name='Application Link')),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_links', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Application Option',
                'verbose_name_plural': 'Multiple Application Options',
                'ordering': ['order', 'id'],
            },
        ),
    ]
