# Generated by Django 5.2.16 on 2026-08-07 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_deadline_text_alter_job_application_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Defaults to right now, but you can set this to any date/time — useful for backdating a listing.', verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='trendingtopic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Defaults to right now, but you can set this to any date/time — useful for backdating an entry.', verbose_name='Date Added'),
        ),
    ]
