# Generated by Django 5.2.6 on 2026-09-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry-level / No experience'), ('1_2', '1–2 years'), ('3_5', '3–5 years'), ('5_plus', '5+ years'), ('senior', 'Senior / Executive')], help_text="Powers the 'Experience' search filter. Leave blank if not specified.", max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'IT & Technology'), ('finance', 'Finance & Accounting'), ('healthcare', 'Healthcare'), ('education', 'Education & Training'), ('engineering', 'Engineering'), ('retail', 'Retail & Sales'), ('government', 'Government & Public Sector'), ('marketing', 'Marketing & Communications'), ('agriculture', 'Agriculture'), ('construction', 'Construction & Built Environment'), ('logistics', 'Logistics & Supply Chain'), ('hospitality', 'Hospitality & Tourism'), ('legal', 'Legal'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], help_text="Powers the 'Industry' search filter. Leave blank if not specified.", max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification_level',
            field=models.CharField(blank=True, choices=[('none', 'No formal qualification required'), ('matric', 'Matric / Grade 12'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('honours', 'Honours Degree'), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], help_text="Powers the 'Qualification' search filter. Leave blank if not specified.", max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, help_text="Optional whole number, e.g. 15000. Only used to power the 'minimum salary' search filter — it is NOT shown to job seekers; the Salary field above is still what's displayed.", null=True, verbose_name='Minimum salary (for filtering only)'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], help_text="Powers the 'Remote/On-site' search filter. Leave blank if not specified.", max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text="Powers the 'Skill' search filter and the Job-Market Analytics 'most requested skills' chart.", related_name='jobs', to='jobs.skill'),
        ),
    ]
