# Generated by Django 5.2.6 on 2026-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_skill_job_experience_level_job_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills that commonly go together, e.g. Statistics ↔ Data Analysis. Works both ways automatically. Used to suggest skills to job seekers.', to='jobs.skill'),
        ),
    ]
