# Generated by Django 5.2.6 on 2026-09-25 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0009_skill_job_experience_level_job_industry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('level', models.CharField(blank=True, choices=[('none', 'No formal qualification required'), ('matric', 'Matric / Grade 12'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('honours', 'Honours Degree'), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], help_text="Roughly where this sits among the site's qualification levels — optional, helps with matching in a later phase.", max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('milestones', models.TextField(blank=True, help_text="Optional. One milestone per line, in the order a job seeker would tackle them, e.g. 'Learn Python basics'.")),
                ('icon', models.CharField(blank=True, help_text='An emoji, e.g. 📊', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='career_paths', to='jobs.skill')),
                ('qualifications', models.ManyToManyField(blank=True, related_name='career_paths', to='accounts.qualification')),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='e.g. Johannesburg, Gauteng', max_length=100)),
                ('qualification_level', models.CharField(blank=True, choices=[('none', 'No formal qualification required'), ('matric', 'Matric / Grade 12'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('honours', 'Honours Degree'), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=20, verbose_name='Highest qualification level')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry-level / No experience'), ('1_2', '1–2 years'), ('3_5', '3–5 years'), ('5_plus', '5+ years'), ('senior', 'Senior / Executive')], max_length=20)),
                ('career_goal', models.CharField(blank=True, help_text="What role or field are you working towards? e.g. 'Data Analyst'", max_length=150)),
                ('bio', models.TextField(blank=True, help_text='A short summary about yourself (optional).', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualifications', models.ManyToManyField(blank=True, help_text='Your specific qualification(s).', related_name='profiles', to='accounts.qualification')),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='jobs.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
