# Generated by Django 5.2.6 on 2026-09-25 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0009_skill_job_experience_level_job_industry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='saved', max_length=20)),
                ('applied_at', models.DateField(blank=True, null=True, verbose_name='Date applied')),
                ('reminder_date', models.DateField(blank=True, help_text='Optional — e.g. a follow-up date or interview date. Shown on your tracker as it gets close.', null=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('reached_interview', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracked Job',
                'verbose_name_plural': 'Tracked Jobs',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
