# Generated by Django 5.2.6 on 2026-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savedsearch'),
        ('jobs', '0010_skill_related_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='job_titles',
            field=models.TextField(blank=True, help_text="Optional. One job title per line (e.g. 'Data Analyst', 'BI Analyst'). Listings whose title contains any of these show up as related jobs.", verbose_name='Related job titles'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='next_paths',
            field=models.ManyToManyField(blank=True, help_text='Careers people typically move on to from this one, e.g. Data Analyst → Data Scientist.', related_name='previous_paths', to='accounts.careerpath', verbose_name='Next career steps'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills this qualification usually covers. Suggested to job seekers who list it.', related_name='qualifications', to='jobs.skill'),
        ),
    ]
